"""
evaluate.py — Model Evaluation
Calculates RMSE for each volatility model against realized volatility.
Plots 95% confidence intervals.
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from src.data_loader import download_data

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'output')
os.makedirs(OUTPUT_DIR, exist_ok=True)


def run_evaluation(ticker="RELIANCE.NS", years=5):
    print(f"[Evaluate] Running model evaluation for {ticker}...")

    # Check if predicted volatility CSV exists (generated by models.py)
    pred_file = os.path.join(OUTPUT_DIR, f'{ticker}_predicted_volatility.csv')
    if not os.path.exists(pred_file):
        print(f"[Evaluate] ⚠️  {pred_file} not found. Running models.py first...")
        from docs.models import fit_volatility_models
        fit_volatility_models(ticker, years)

    if not os.path.exists(pred_file):
        print("[Evaluate] ❌ Cannot proceed without predicted volatility data.")
        return

    df = download_data(ticker, years=years)
    if df is None:
        return

    pred_df = pd.read_csv(pred_file, index_col=0, parse_dates=True)

    # Realized volatility proxy
    real_returns = df['Log_Return'] * 100
    realized_vol = real_returns.rolling(window=21).std()

    # RMSE for each model
    results = {}
    for col in pred_df.columns:
        valid_idx = realized_vol.dropna().index.intersection(pred_df.index)
        if len(valid_idx) == 0:
            continue
        rmse = np.sqrt(mean_squared_error(realized_vol.loc[valid_idx], pred_df.loc[valid_idx, col]))
        results[col] = rmse
        print(f"  RMSE {col:12s}: {rmse:.4f}")

    # Best model
    if results:
        best = min(results, key=results.get)
        print(f"\n  🏆 Best model: {best} (RMSE: {results[best]:.4f})")

    # 95% Confidence Interval plot
    primary_model = 'GARCH' if 'GARCH' in pred_df.columns else pred_df.columns[0]
    mu = real_returns.mean()
    vol = pred_df[primary_model]

    plt.figure(figsize=(14, 6))
    plt.plot(real_returns, color='gray', alpha=0.25, linewidth=0.5, label='Actual Returns')
    plt.fill_between(vol.index, mu - 1.96 * vol, mu + 1.96 * vol,
                     color='#ef4444', alpha=0.15, label='95% CI')
    plt.plot(mu + 1.96 * vol, color='#ef4444', linestyle='--', alpha=0.5, linewidth=0.7)
    plt.plot(mu - 1.96 * vol, color='#ef4444', linestyle='--', alpha=0.5, linewidth=0.7)
    plt.title(f'{ticker} — 95% Confidence Intervals ({primary_model})', fontweight='bold')
    plt.legend()
    plt.tight_layout()
    plot_path = os.path.join(OUTPUT_DIR, f'{ticker}_confidence_intervals.png')
    plt.savefig(plot_path, dpi=150)
    plt.close()

    # Save stats
    stats_df = pd.DataFrame(results.items(), columns=['Model', 'RMSE'])
    stats_path = os.path.join(OUTPUT_DIR, f'{ticker}_evaluation_stats.csv')
    stats_df.to_csv(stats_path, index=False)

    print(f"\n[Evaluate] ✅ Plot: {plot_path}")
    print(f"[Evaluate] ✅ Stats: {stats_path}")
    return results


if __name__ == "__main__":
    ticker = sys.argv[1] if len(sys.argv) > 1 else "RELIANCE.NS"
    run_evaluation(ticker)
